# Generated by Django 4.1.5 on 2023-02-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='details',
            field=models.CharField(default=123, max_length=500),
            preserve_default=False,
        ),
    ]
